import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { EthosConnectProvider, SignInButton, ethos, EthosConnectStatus } from 'ethos-connect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { status, wallet } = ethos.useWallet();

  return (
    <>
      <EthosConnectProvider>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div> status: {status} </div>
          <div> wallet: {wallet?.address} </div>

          {status === EthosConnectStatus.Loading ? (
            <div>
              Loading...
              <SignInButton />

            </div>
          ) : status === EthosConnectStatus.NoConnection ? (
            <div>
              No wallet connected
              <SignInButton />
            </div>
          ) : (
            // status is EthosConnectStatus.Connected
            <div>
              Wallet connected

            </div>
          )}
        </main>
      </EthosConnectProvider>
    </>
  )
}
